'use strict';

export default {
    SELECT_TAB: 'SELECT_TAB',

    MAP_ON_CLICK: 'MAP_ON_CLICK',
    MAP_ON_CHANGE: 'MAP_ON_CHANGE',

    DATASET_FETCH_REQUESTED: 'DATASET_FETCH_REQUESTED',
    DATASET_FETCH_SUCCEEDED: 'DATASET_FETCH_SUCCEEDED',
    SAMPLE_FETCH_REQUESTED: 'SAMPLE_FETCH_REQUEST',
    SAMPLE_FETCH_SUCCEEDED: 'SAMPLE_FETCH_SUCEEDED',

    STATE_REPLACE: 'STATE_REPLACE'
};